# Конфигурационный файл SNSocialMedia для Spigot

# Настройки подключения к Velocity
velocity:
  # Канал связи
  channel: "snsocialmedia:main"
  # Секретный ключ для защиты канала (замените на свой собственный ключ)
  secret: "change_this_to_a_secure_key"

# Настройки GUI
gui:
  # Обновлять интерфейсы автоматически
  auto-update: true
  # Интервал обновления интерфейсов в тиках (20 тиков = 1 секунда)
  update-interval: 20
  # Включить GUI для всех настроек
  enabled: true

# Настройки системы Гильдий
guilds:
  # Включить функционал гильдий на этом сервере
  enabled: true
  # Включить GUI для гильдий
  gui-enabled: true
  # Максимальное количество участников в гильдии
  max-members: 50
  # Максимальная длина названия гильдии
  max-name-length: 16
  # Минимальная длина названия гильдии
  min-name-length: 3
  # Стоимость создания гильдии
  creation-cost: 1000

# Настройки системы Друзей
friends:
  # Включить функционал друзей на этом сервере
  enabled: true
  # Включить GUI для друзей
  gui-enabled: true
  # Максимальное количество друзей
  max-friends: 100

# Настройки системы Пати
party:
  # Включить функционал пати на этом сервере
  enabled: true
  # Включить GUI для пати
  gui-enabled: true
  # Включить телепортацию участников пати к лидеру
  teleport-enabled: true
  # Максимальное количество участников в пати
  max-members: 8

# Настройки базы данных MySQL
database:
  host: "localhost"
  port: 3306
  name: "snsocialmedia"
  username: "snsocialuser"
  password: "Hihet1597531782"
  pool-size: 10

# Настройки хранилища гильдий
storage:
  # Начальное количество слотов для хранилища
  initial-slots: 10
  # Максимальное количество слотов для хранилища
  max-slots: 100
  # Стоимость обновления хранилища (за каждый добавляемый слот)
  upgrade-cost-per-slot: 1000
  # Процентная ставка для начисления процентов на баланс гильдий (0.01 = 1%)
  interest_rate: 0.01
  # Интервал начисления процентов в днях (не используется, задано через код)
  # interest_interval_days: 1
  
  # Типы обновлений хранилища
  upgrade-types:
    small:
      name: "Небольшое обновление"
      slots: 5
      cost: 5000
      description: "Добавляет 5 дополнительных слотов в хранилище гильдии"
      icon: "CHEST"
    medium:
      name: "Среднее обновление"
      slots: 10
      cost: 9000
      description: "Добавляет 10 дополнительных слотов в хранилище гильдии"
      icon: "ENDER_CHEST"
    large:
      name: "Большое обновление"
      slots: 20
      cost: 16000
      description: "Добавляет 20 дополнительных слотов в хранилище гильдии"
      icon: "SHULKER_BOX"

# Сообщения
messages:
  prefix: "&8[&c&lSNS&8] &r"
  error-prefix: "&8[&c&lSNS&8] &c"
  
  # Общие сообщения
  no-permission: "У вас недостаточно прав для выполнения этой команды."
  player-only: "Эта команда доступна только для игроков."
  
  # Сообщения для гильдий
  guild:
    not-in-guild: "Вы не состоите в гильдии."
    no-guild-found: "Гильдия не найдена."
    
  # Сообщения для хранилища гильдий
  storage:
    not-enough-space: "Недостаточно места в хранилище гильдии."
    not-enough-items: "Недостаточно предметов в хранилище гильдии."
    not-enough-money: "Недостаточно денег в хранилище гильдии."
    not-enough-player-money: "У вас недостаточно денег."
    deposit-success: "Вы успешно внесли предметы в хранилище."
    withdraw-success: "Вы успешно сняли предметы из хранилища."
    deposit-money-success: "Вы успешно внесли %amount% монет в хранилище гильдии."
    withdraw-money-success: "Вы успешно сняли %amount% монет из хранилища гильдии."
    upgrade-success: "Вы успешно улучшили хранилище гильдии."
    no-permission-withdraw: "У вас нет прав для снятия предметов из хранилища."
    no-permission-deposit: "У вас нет прав для внесения предметов в хранилище."
    no-permission-upgrade: "У вас нет прав для улучшения хранилища."
    guild-id-not-found: "ID гильдии не найден. Пожалуйста, повторите попытку."

# Настройки логирования
logging:
  # Уровень логирования (INFO, WARNING, SEVERE)
  level: "INFO"
  # Логировать действия с хранилищем
  storage-actions: true
  # Логировать ошибки
  errors: true 